version: 2

models:
  - name: dim_channels
    description: "Dimension table containing information about each Telegram channel"
    columns:
      - name: channel_key
        description: "Surrogate key for the channel dimension"
        tests:
          - unique
          - not_null
      
      - name: channel_name
        description: "Channel username/handle"
        tests:
          - unique
          - not_null
      
      - name: channel_title
        description: "Display name of the channel"
      
      - name: channel_type
        description: "Classification of channel (Pharmaceutical, Cosmetics, Medical Equipment)"
        tests:
          - accepted_values:
              values: ['Pharmaceutical', 'Cosmetics', 'Medical Equipment', 'General Medical']
      
      - name: first_post_date
        description: "Date of first message in channel"
        tests:
          - not_null
      
      - name: last_post_date
        description: "Date of most recent message in channel"
        tests:
          - not_null
      
      - name: total_posts
        description: "Total number of messages in channel"
        tests:
          - not_null
      
      - name: avg_views
        description: "Average view count across all channel messages"

  - name: dim_dates
    description: "Date dimension for time-based analysis"
    columns:
      - name: date_key
        description: "Surrogate key in YYYYMMDD format"
        tests:
          - unique
          - not_null
      
      - name: full_date
        description: "Full calendar date"
        tests:
          - unique
          - not_null
      
      - name: day_of_week
        description: "Day of week (0=Sunday, 6=Saturday)"
      
      - name: day_name
        description: "Name of the day (Monday, Tuesday, etc.)"
      
      - name: week_of_year
        description: "Week number of the year (1-53)"
      
      - name: month
        description: "Month number (1-12)"
        tests:
          - accepted_values:
              values: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
      
      - name: month_name
        description: "Name of the month (January, February, etc.)"
      
      - name: quarter
        description: "Quarter of the year (1-4)"
        tests:
          - accepted_values:
              values: [1, 2, 3, 4]
      
      - name: year
        description: "Year"
        tests:
          - not_null

  - name: fct_messages
    description: "Fact table with one row per message"
    columns:
      - name: message_id
        description: "Unique message identifier"
        tests:
          - unique
          - not_null
      
      - name: channel_key
        description: "Foreign key to dim_channels"
        tests:
          - not_null
          - relationships:
              to: ref('dim_channels')
              field: channel_key
      
      - name: date_key
        description: "Foreign key to dim_dates"
        tests:
          - not_null
          - relationships:
              to: ref('dim_dates')
              field: date_key
      
      - name: message_text
        description: "Text content of the message"
      
      - name: message_length
        description: "Length of message text in characters"
      
      - name: view_count
        description: "Number of views for the message"
        tests:
          - not_null
      
      - name: forward_count
        description: "Number of times message was forwarded"
        tests:
          - not_null
      
      - name: has_image
        description: "Whether message contains an image"
